---
deployment:
  tasks:
    - export DEPLOYPATH=/home/daniofkr/public_html/
    - cp index.html $DEPLOYPATH
    - cp -r css $DEPLOYPATH
    - cp -r html $DEPLOYPATH
    - cp -r js $DEPLOYPATH
    - cp -r resources $DEPLOYPATH