---
deployment:
  tasks:
    - export DEPLOYPATH=/home/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R html $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH